### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by xieyuheng**

### CODE REVIEW

**Comment by carlsmith** [comment]
Sorry I didn't respond sooner. Thank you though. Cheers.

**Comment by xieyuheng** [comment]
---

your project is so cool :)

for me, it looks like an emacs on the web

---

but
I still need to learn much about js and coffee to hack it

so many libraries is used
but I am so un-familiar with the ecosystem of js

I wish to see more documentations
about the use of these libraries
for non js expert
[when you have time of course]

---

**Comment by carlsmith** [comment]
Thanks. I really do need to write some docs for it. There are docs built in, but they're a bit like API docs, and don't explain the overall shell well at all. They don't even really show anything you can do with it, just how all the bits work.

You can find out all the Sugar methods from [their site](http://sugarjs.com). Just click on API, then the type, like String or Array. All the methods documented there are available in cosh on all native types.

jQuery is super [well documented](https://jquery.com) too. It's available globally as `jQuery` and `$`.

They are the main two libraries that you really use.

You're right though, I should write some stuff to show how that all fits together in the shell.

**Comment by xieyuheng** [comment]
with your help, I would be able to write some doc for you when I am learning it.

but problem is
I use the org-mode of emacs to do literate programming
instead of .coffee.md

I won't be able to PR to you from my main branch
but I can help about the documentations anyway ~

**Comment by carlsmith** [comment]
No worries. Anything you can do would be appreciated. I don't mind helping fix things to make them fit. Thank you.

I wrote [an intro](https://gist.github.com/carlsmith/8623a1a6c1625c96a67d) you may want to have a look at. It's not a great tutorial, as I chucked it together real fast. Still, it shows how to create a basic utility, how to publish and push changes to it, and how to view it online and share the link.

Thanks again.

**Pull request merged**
